name = "VRPTW"
uuid = "98e944a4-2f93-413e-9005-d4dae69c2efa"
authors = ["Payakorn Saksuriya"]
version = "0.1.0"

[deps]
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
JLD2 = "0.4"
Revise = "3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
